default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Development uses local PG by default.
# Set DATABASE_URL to connect to production instead:
#   DATABASE_URL=postgres://... bin/rails c
development:
  <<: *default
  database: disqrails_development
  host: localhost

test:
  <<: *default
  database: disqrails_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
    schema_dump: db/queue_schema.rb
